backup_directory: pipeline_backups
confidence_level: 0.95
create_thesis_package: true
cv_folds: 5
enable_data_cleaning: true
enable_data_validation: true
enable_feature_engineering: true
enable_model_checkpoints: true
enable_model_optimization: true
enable_organizational_data: true
enable_real_time_api: false
export_clean_data: true
generate_visualizations: true
max_missing_threshold: 0.1
min_class_samples: 10
output_directory: pipeline_results
project_name: Student_Achievement_Classification
random_state: 42
raw_data_path: demo_mahasiswa.csv
test_size: 0.2
version: 1.0.0
